[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
blueshift_anchor_escrow = "9bzLabgRbTMTVk4yQEoE26RkhpWg8XJJbLY9muqioder"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
