cargo-features = ["edition2024"]

[package]
name = "blueshift_vault"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pinocchio = "0.8.4"
pinocchio-system = "0.2.3"
pinocchio-token = "0.3.0"
